environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      -
        self:
          namespace: unique

---
releases:
  - name: redis-secret
    chart: oci://ghcr.io/unique-ag/helm-charts/sscsid-keeper
    version: 1.1.5
    namespace: {{ .Values.self.namespace }}
    wait: false
    values:
      -
        keeper:
          image:
            repository: {{ .Values.plain.registryUrl }}/busybox
            tag: "1.37"
        spc:
          kvName: {{ .Values.params.keyVaults.sensitive.name }}
          tenantId: {{ requiredEnv "ARM_TENANT_ID" }}
          identityId: {{ .Values.params.identities.keyVaultSecretsProvider.clientId }}
          secrets:
            - k8sSecretDataKey: {{ .Values.plain.redis.secret.secretKeyName }}
              kvObjectName: {{ .Values.plain.redis.secret.kvSecretName }}
