environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      - ../../versions.yaml
      -
        self:
          namespace: unique

---

releases:

  - name: backend-service-ingestion
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/ingestion.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-ingestion
        env:

          
          : {{ .Values.plain.zitadel.rootOrgId | quote }}




  - name: backend-service-ingestion-worker
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/ingestion-worker.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-ingestion-worker
        env:

        envVars:
          - name: RABBITMQ_USERNAME #! FIXME: @evrim should refactor to respect AMQP_USERNAME as well
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: RABBITMQ_PASSWORD #! FIXME: @evrim should refactor to respect AMQP_PASSWORD as well
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: host
          - name: AMQP_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: port
        secretProvider:
          tenantId: {{ requiredEnv "ARM_TENANT_ID" }}
          userAssignedIdentityID: {{ .Values.params.identities.keyVaultSecretsProvider.clientId }}
          vaults:
            helloazuremain:
              AZURE_OPENAI_API_ENDPOINT: {{ .Values.kvRefs.aoi.apiEndpoint }}
              AZURE_DOCUMENT_INTELLIGENCE_ENDPOINTS: {{ .Values.kvRefs.adi.endpoints }}
        serviceAccount:
          workloadIdentity:
            clientId: 0f7cd773-a53a-4b58-8835-146dd20e281b

  - name: backend-service-ingestion-worker-chat
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/ingestion-worker.bs.yaml
      - ./values/ingestion-worker-chat.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-ingestion-worker
        env:

        envVars:
          - name: RABBITMQ_USERNAME #! FIXME: @evrim should refactor to respect AMQP_USERNAME as well
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: RABBITMQ_PASSWORD #! FIXME: @evrim should refactor to respect AMQP_PASSWORD as well
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: host
          - name: AMQP_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: port
        secretProvider:
          tenantId: {{ requiredEnv "ARM_TENANT_ID" }}
          userAssignedIdentityID: {{ .Values.params.identities.keyVaultSecretsProvider.clientId }}
          vaults:
            helloazuremain:
              AZURE_OPENAI_API_ENDPOINT: {{ .Values.kvRefs.aoi.apiEndpoint }}
              AZURE_DOCUMENT_INTELLIGENCE_ENDPOINTS: {{ .Values.kvRefs.adi.endpoints }}
        serviceAccount:
          workloadIdentity:
            clientId: 0f7cd773-a53a-4b58-8835-146dd20e281b
