environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      -
        self:
          namespace: unique

repositories:
  - name: qdrant
    url: https://qdrant.github.io/qdrant-helm

releases:
  - name: qdrant
    chart: qdrant/qdrant
    version: 1.13.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - replicaCount: 1
        image:
          repository: {{ .Values.plain.registryUrl }}/qdrant/qdrant
          tag: v1.13.1
          useUnprivilegedImage: true # auto-appends -unprivileged to the tag
        updateVolumeFsOwnership: false # as this is a new cluster, the file system was never running as root
        resources:
          requests:
            cpu: 100m
            memory: 1.8Gi
          limits:
            memory: 2Gi
        nodeSelector:
          pool: stable
        persistence:
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          storageClassName: default-zrs
        startupProbe:
          enabled: true
          failureThreshold: 30
          periodSeconds: 30
