environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      - ../../versions.yaml
      -
        self:
          namespace: unique

---

releases:
  - name: web-app-chat
    chart: oci://ghcr.io/unique-ag/helm-charts/web-app
    version: 3.1.0
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/chat.wa.yaml
      -
        image:
          tag: {{ index .Values.versions.chat.webApp "chat" }}
          repository: {{ .Values.plain.registryUrl }}/web-app-chat
        env:
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.{{ .Values.params.zoneName }} *.core.windows.net wss://*.{{ .Values.params.zoneName }}; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.{{ .Values.params.zoneName }};"
          ADMIN_APP_URL: https://{{ .Values.params.zoneName }}/admin
          INGESTION_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/ingestion
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/scope-management
          SELF_URL: https://{{ .Values.params.zoneName }}/chat
          CHAT_APP_URL: https://{{ .Values.params.zoneName }}/chat
          CHAT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/chat
          KNOWLEDGE_UPLOAD_APP_URL: https://{{ .Values.params.zoneName }}/knowledge-upload
          STATIC_BACKGROUND_COLOR: "#F7F7F7"
          STATIC_TAB_NAME: "Hello Azure"
          STATIC_THEME_COLORS: >-
            {"color-primary-cta": "#8D4C82", "color-primary-variant": "#744B6D", "color-secondary": "#5b5b5b", "color-secondary-variant": "#3e3e3e", "color-background": "#f6f6f6", "color-background-variant": "#ececec", "color-surface": "#ffffff", "color-control": "#cfcfcf", "color-info": "#4167a6", "color-success-light": "#ebfaf2", "color-success-dark": "#0f9451", "color-error-light": "#cc5e71", "color-error-dark": "#d12a46", "color-attention": "#db7600", "color-attention-variant": "#8d4c82", "color-on-primary": "#ffffff", "color-on-secondary": "#ffffff", "color-on-background-main": "#3e3e3e", "color-on-background-dimmed": "#787878", "color-on-surface": "#3e3e3e", "color-on-control-main": "#3e3e3e", "color-on-control-dimmed": "#b3b3b3", "color-on-info": "#ffffff", "color-on-success-light": "#3e3e3e", "color-on-success-dark": "#ffffff", "color-on-error-light": "#ffffff", "color-on-error-dark": "#ffffff", "color-on-attention": "#ffffff", "color-on-attention-variant": "#ffffff"}
          THEME_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/theme
          ZITADEL_CLIENT_ID: {{ .Values.plain.zitadel.clientId | quote }}
          ZITADEL_ISSUER: {{ printf "%s%s.%s" "https://" .Values.plain.zitadel.subDomainName .Values.params.zoneName }}
          ZITADEL_ORG_ID: ""
          ZITADEL_PROJECT_ID: {{ .Values.plain.zitadel.projectId | quote }}
        extraObjects:
          - apiVersion: configuration.konghq.com/v1
            kind: KongPlugin
            metadata:
              name: uniquens-chat-redirect
            plugin: redirect
            config:
              location: https://{{ .Values.params.zoneName }}/chat
        extraRoutes:
          root-redirect:
            hostnames:
              - {{ .Values.params.zoneName }}
        routes:
          hostname: {{ .Values.params.zoneName }}

  - name: web-app-knowledge-upload
    chart: oci://ghcr.io/unique-ag/helm-charts/web-app
    version: 3.1.0
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/knowledge-upload.wa.yaml
      -
        image:
          tag: {{ index .Values.versions.chat.webApp "knowledge-upload" }}
          repository: {{ .Values.plain.registryUrl }}/web-app-knowledge-upload
        env:
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.{{ .Values.params.zoneName }} *.core.windows.net wss://*.{{ .Values.params.zoneName }}; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.{{ .Values.params.zoneName }};"
          ADMIN_APP_URL: https://{{ .Values.params.zoneName }}/admin
          INGESTION_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/ingestion
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/scope-management
          SELF_URL: https://{{ .Values.params.zoneName }}/knowledge-upload
          CHAT_APP_URL: https://{{ .Values.params.zoneName }}/chat
          CHAT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/chat
          KNOWLEDGE_UPLOAD_APP_URL: https://{{ .Values.params.zoneName }}/knowledge-upload
          STATIC_BACKGROUND_COLOR: "#F7F7F7"
          STATIC_TAB_NAME: "Hello Azure"
          STATIC_THEME_COLORS: >-
            {"color-primary-cta": "#8D4C82", "color-primary-variant": "#744B6D", "color-secondary": "#5b5b5b", "color-secondary-variant": "#3e3e3e", "color-background": "#f6f6f6", "color-background-variant": "#ececec", "color-surface": "#ffffff", "color-control": "#cfcfcf", "color-info": "#4167a6", "color-success-light": "#ebfaf2", "color-success-dark": "#0f9451", "color-error-light": "#cc5e71", "color-error-dark": "#d12a46", "color-attention": "#db7600", "color-attention-variant": "#8d4c82", "color-on-primary": "#ffffff", "color-on-secondary": "#ffffff", "color-on-background-main": "#3e3e3e", "color-on-background-dimmed": "#787878", "color-on-surface": "#3e3e3e", "color-on-control-main": "#3e3e3e", "color-on-control-dimmed": "#b3b3b3", "color-on-info": "#ffffff", "color-on-success-light": "#3e3e3e", "color-on-success-dark": "#ffffff", "color-on-error-light": "#ffffff", "color-on-error-dark": "#ffffff", "color-on-attention": "#ffffff", "color-on-attention-variant": "#ffffff"}
          THEME_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/theme
          ZITADEL_CLIENT_ID: {{ .Values.plain.zitadel.clientId | quote }}
          ZITADEL_ISSUER: {{ printf "%s%s.%s" "https://" .Values.plain.zitadel.subDomainName .Values.params.zoneName }}
          ZITADEL_ORG_ID: ""
          ZITADEL_PROJECT_ID: {{ .Values.plain.zitadel.projectId | quote }}
        routes:
          hostname: {{ .Values.params.zoneName }}

  - name: web-app-theme
    chart: oci://ghcr.io/unique-ag/helm-charts/web-app
    version: 3.1.0
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/theme.wa.yaml
      -
        image:
          tag: {{ index .Values.versions.chat.webApp "theme" }}
          repository: {{ .Values.plain.registryUrl }}/web-app-theme
        env:
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.{{ .Values.params.zoneName }} *.core.windows.net wss://*.{{ .Values.params.zoneName }}; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.{{ .Values.params.zoneName }};"
          ADMIN_APP_URL: https://{{ .Values.params.zoneName }}/admin
          INGESTION_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/ingestion
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/scope-management
          SELF_URL: https://{{ .Values.params.zoneName }}/theme
          CHAT_APP_URL: https://{{ .Values.params.zoneName }}/chat
          CHAT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/chat
          KNOWLEDGE_UPLOAD_APP_URL: https://{{ .Values.params.zoneName }}/knowledge-upload
          STATIC_BACKGROUND_COLOR: "#F7F7F7"
          STATIC_TAB_NAME: "Hello Azure"
          STATIC_THEME_COLORS: >-
            {"color-primary-cta": "#8D4C82", "color-primary-variant": "#744B6D", "color-secondary": "#5b5b5b", "color-secondary-variant": "#3e3e3e", "color-background": "#f6f6f6", "color-background-variant": "#ececec", "color-surface": "#ffffff", "color-control": "#cfcfcf", "color-info": "#4167a6", "color-success-light": "#ebfaf2", "color-success-dark": "#0f9451", "color-error-light": "#cc5e71", "color-error-dark": "#d12a46", "color-attention": "#db7600", "color-attention-variant": "#8d4c82", "color-on-primary": "#ffffff", "color-on-secondary": "#ffffff", "color-on-background-main": "#3e3e3e", "color-on-background-dimmed": "#787878", "color-on-surface": "#3e3e3e", "color-on-control-main": "#3e3e3e", "color-on-control-dimmed": "#b3b3b3", "color-on-info": "#ffffff", "color-on-success-light": "#3e3e3e", "color-on-success-dark": "#ffffff", "color-on-error-light": "#ffffff", "color-on-error-dark": "#ffffff", "color-on-attention": "#ffffff", "color-on-attention-variant": "#ffffff"}
          THEME_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/theme
          ZITADEL_CLIENT_ID: {{ .Values.plain.zitadel.clientId | quote }}
          ZITADEL_ISSUER: {{ printf "%s%s.%s" "https://" .Values.plain.zitadel.subDomainName .Values.params.zoneName }}
          ZITADEL_ORG_ID: ""
          ZITADEL_PROJECT_ID: {{ .Values.plain.zitadel.projectId | quote }}
        routes:
          hostname: {{ .Values.params.zoneName }}

  - name: web-app-admin
    chart: oci://ghcr.io/unique-ag/helm-charts/web-app
    version: 3.1.0
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/admin.wa.yaml
      -
        image:
          tag: {{ index .Values.versions.chat.webApp "admin" }}
          repository: {{ .Values.plain.registryUrl }}/web-app-admin
        env:
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.{{ .Values.params.zoneName }} *.core.windows.net wss://*.{{ .Values.params.zoneName }}; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.{{ .Values.params.zoneName }};"
          ADMIN_APP_URL: https://{{ .Values.params.zoneName }}/admin
          INGESTION_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/ingestion
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/scope-management
          SELF_URL: https://{{ .Values.params.zoneName }}/admin
          CHAT_APP_URL: https://{{ .Values.params.zoneName }}/chat
          CHAT_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/chat
          KNOWLEDGE_UPLOAD_APP_URL: https://{{ .Values.params.zoneName }}/knowledge-upload
          STATIC_BACKGROUND_COLOR: "#F7F7F7"
          STATIC_TAB_NAME: "Hello Azure"
          STATIC_THEME_COLORS: >-
            {"color-primary-cta": "#8D4C82", "color-primary-variant": "#744B6D", "color-secondary": "#5b5b5b", "color-secondary-variant": "#3e3e3e", "color-background": "#f6f6f6", "color-background-variant": "#ececec", "color-surface": "#ffffff", "color-control": "#cfcfcf", "color-info": "#4167a6", "color-success-light": "#ebfaf2", "color-success-dark": "#0f9451", "color-error-light": "#cc5e71", "color-error-dark": "#d12a46", "color-attention": "#db7600", "color-attention-variant": "#8d4c82", "color-on-primary": "#ffffff", "color-on-secondary": "#ffffff", "color-on-background-main": "#3e3e3e", "color-on-background-dimmed": "#787878", "color-on-surface": "#3e3e3e", "color-on-control-main": "#3e3e3e", "color-on-control-dimmed": "#b3b3b3", "color-on-info": "#ffffff", "color-on-success-light": "#3e3e3e", "color-on-success-dark": "#ffffff", "color-on-error-light": "#ffffff", "color-on-error-dark": "#ffffff", "color-on-attention": "#ffffff", "color-on-attention-variant": "#ffffff"}
          THEME_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/theme
          ZITADEL_CLIENT_ID: {{ .Values.plain.zitadel.clientId | quote }}
          ZITADEL_ISSUER: {{ printf "%s%s.%s" "https://" .Values.plain.zitadel.subDomainName .Values.params.zoneName }}
          ZITADEL_ORG_ID: ""
          ZITADEL_PROJECT_ID: {{ .Values.plain.zitadel.projectId | quote }}
          APP_REPOSITORY_BACKEND_API_URL: https://{{ printf "%s.%s" .Values.plain.apiGateway.subDomainName .Values.params.zoneName }}/apps
        routes:
          hostname: {{ .Values.params.zoneName }}
