environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      - ../../versions.yaml
      -
        self:
          namespace: unique

---

releases:
  - name: backend-service-webhook-worker
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/webhook-worker.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-webhook-worker
        envVars:
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: host
          - name: AMQP_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: port

  - name: backend-service-webhook-scheduler
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/webhook-scheduler.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-webhook-scheduler
        envVars:
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: host
          - name: AMQP_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: port

  - name: backend-service-event-socket
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/event-socket.bs.yaml
      -
        image:
          tag: "2025.04"
          repository: uniquehelloazure.azurecr.io/backend-service-event-socket
        env:
          ZITADEL_PROJECT_ID: {{ .Values.plain.zitadel.projectId | quote }}
        envVars:
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: username
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: password
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: host
          - name: AMQP_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmqcluster-chat-default-user
                key: port
        routes:
          hostname: api.gateway.azure.unique.dev

  - name: client-insights-exporter
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 3.1.1
    namespace: {{ .Values.self.namespace }}
    createNamespace: true
    wait: false
    values:
      - ./values/client-insights-exporter.bs.yaml
      -
        image:
          tag: "2025.04"
