environments:
  default:
    values:
      - ../../params.yaml
      - ../../terraform-outputs.yaml
      -
        self:
          namespace: unique

---

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts

releases:
  # We need to manually create the secret for the rabbitmq cluster in order to be able to use the credentials in two namespaces
  # https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/external-admin-secret-credentials
  - name: rabbitmqcluster-chat-unique-user
    chart: bedag/raw
    version: 2.0.0
    namespace: {{ .Values.self.namespace }}
    wait: false
    values:
      - resources:
        - apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: {{ .Values.plain.rabbit.secret.secretName }}
          stringData:
            default_user.conf: |
              default_user = {{ .Values.plain.rabbit.username }}
              default_pass = {{ printf "%s%s/%s" "ref+azurekeyvault://" .Values.params.keyVaults.sensitive.name .Values.kvRefs.rabbit.password | fetchSecretValue }}
            host: rabbitmqcluster-chat.unique.svc.cluster.local
            username: {{ .Values.plain.rabbit.username }}
            password: {{ printf "%s%s/%s" "ref+azurekeyvault://" .Values.params.keyVaults.sensitive.name .Values.kvRefs.rabbit.password | fetchSecretValue }}
            port: "5672"
            provider: rabbitmq
            type: rabbitmq
