auditVolume:
  enabled: true
  mountPath: /audit
  attributes:
    resourceGroup: ref+azurekeyvault://helloazuresensitive/audit-storage-resource-group
    storageAccount: ref+azurekeyvault://helloazuresensitive/audit-storage-account-name
image:
  repository: uniquehelloazure.azurecr.io/backend-service-configuration
  tag: "2025.44.1"
secretProvider:
  vaults:
    helloazuresensitive:
      DATABASE_URL: database-url-theme
      AUDIT_STORAGE_RESOURCE_GROUP: audit-storage-resource-group
      AUDIT_STORAGE_ACCOUNT_NAME: audit-storage-account-name
