auditVolume:
  attributes:
    resourceGroup: unset_default_value
    storageAccount: unset_default_value
image:
  repository: uniquehelloazure.azurecr.io/backend-service-configuration
  tag: "2025.48.2"
secretProvider:
  vaults:
    helloazuresensitive:
      DATABASE_URL: database-url-theme
