keeper:
  image:
    repository: uniquehelloazure.azurecr.io/busybox
    tag: 1.37
spc:
  kvName: helloazuresensitive
  tenantId: aeade8c4-d4f7-4ae7-9149-4975fa3a7f91
  identityId: 656b2988-6508-4df3-ba88-5a0d721863ae
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
  secrets:
    - k8sSecretDataKey: oidc.azure.client_id
      kvObjectName: aad-app-hello-azure-gitops-client-id
    - k8sSecretDataKey: oidc.azure.client_secret
      kvObjectName: aad-app-hello-azure-gitops-client-secret