keeper:
  image:
    repository: uniquehelloazure.azurecr.io/busybox
    tag: 1.37
spc:
  kvName: helloazuresensitive
  tenantId: aeade8c4-d4f7-4ae7-9149-4975fa3a7f91
  identityId: 874387d6-a672-4ee9-9de5-b9b2dc4d2b61
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
  secrets:
    - k8sSecretDataKey: oidc.azure.client_id
      kvObjectName: aad-app-hello-azure-gitops-client-id
    - k8sSecretDataKey: oidc.azure.client_secret
      kvObjectName: aad-app-hello-azure-gitops-client-secret