plain:
  apiGateway:
    subDomainName: api
  clusterIssuer:
    name: letsencrypt-azure-dns
    server: https://acme-v02.api.letsencrypt.org/directory
  rabbit:
    secret:
      secretName: rabbitmqcluster-chat-default-user
    username: helloazuredev
  redis:
    secret:
      secretKeyName: pass
      secretName: redis-secret-sscsid-keeper
      # kvSecretName: filled-by-jinja
  # sdkDeploy: # todo
  #   botObjectId: 83352105-b3ab-40b2-a386-cef6372d1b04
  #   key1:
  #     kvSecretName: sops-age-key-1
  #     secretKeyName: SOPS_AGE_KEY_1
  #   key2:
  #     kvSecretName: sops-age-key-2
  #     secretKeyName: SOPS_AGE_KEY_2
  zitadel: # to be filled after initial Zitadel deployment
    clientId: '305512969981198951'
    projectId: '305512913743905383'
    rootOrgId: ''
    secretCerts:
      secretName: zitadel-certs
    secretMasterKey:
      secretKeyName: masterkey
      secretName: zitadel-secret-sscsid-keeper
    subDomainName: id