# we could Jinja template this file, but for now lets keep it simple
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chat
  namespace: unique
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Unique-AG/hello-azure
      revision: preview
      files:
      - path: "applications/aks/gitops/*.app.yaml"
  template:
    metadata:
      name: '{{ .spec.name }}'
      namespace: unique
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: unique
  templatePatch: |
    spec:
      {{- if .spec.autoSync }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      {{- end }}