env:
  MAX_HEAP_MB: 350
nodeSelector:
  pool: stable
probes:
  liveness:
    httpGet:
      path: /knowledge-upload/api/health
      port: http
    initialDelaySeconds: 5
  readiness:
    httpGet:
      path: /knowledge-upload/api/health
      port: http
    initialDelaySeconds: 5
replicaCount: 2
resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 450Mi
routes:
  hostname: unset_default_value
  pathPrefix: /knowledge-upload
  paths:
    default:
      enabled: true
strategy:
  type: Recreate
