env:
  MAX_HEAP_MB: 200
nodeSelector:
  pool: stable
probes:
  liveness:
    httpGet:
      path: /theme/api/health
      port: http
    initialDelaySeconds: 5
  readiness:
    httpGet:
      path: /theme/api/health
      port: http
    initialDelaySeconds: 5
replicaCount: 2
resources:
  limits:
    cpu: 100m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 300Mi
routes:
  hostname: unset_default_value
  pathPrefix: /theme
  paths:
    default:
      enabled: true
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
strategy:
  type: Recreate
