env:
  APP_REPOSITORY_URL: http://backend-service-app-repository.unique.svc
  LOG_LEVEL: debug
  MAX_HEAP_MB: 200
nodeSelector:
  scalability: steady
  lifecycle: persistent
probes:
  enabled: false
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 300Mi
