# we could Jinja template this file, but for now lets keep it simple
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chat
  namespace: unique
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Unique-AG/hello-azure
      revision: main
      files:
      - path: "20_k8s_workloads/argo/chat/*.app.yaml"
  template:
    metadata:
      name: '{{ .spec.name }}'
      namespace: unique
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: unique
  templatePatch: |
    spec:
      {{- if hasKey .spec "sources" }}
      sources:
        {{- .spec.sources | toYaml | nindent 4 }}
      {{- else }}
      source:
        {{- .spec.source | toYaml | nindent 4 }}
      {{- end }}
      {{- if hasKey .spec "additionalValues" }}
      {{- .spec.additionalValues | toYaml | nindent 2 }}
      {{- end }}
      {{- if .spec.autoSync }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      {{- end }}