apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-chat
spec:
  image: uniquehelloazure.azurecr.io/bitnami/rabbitmq:3.13.7-debian-12-r3
  replicas: 1
  resources:
    requests:
      cpu: '1'
      memory: 1Gi
    limits:
      memory: 1Gi
  secretBackend:
    externalSecret:
      name: rabbitmqcluster-chat-default-user
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: default-zrs
    storage: "50Gi"
  affinity:
    podAntiAffinity:
      # prod: requiredDuringSchedulingIgnoredDuringExecution {different child settings}
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmqcluster-chat
          topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
            initContainers:
            - name: setup-container
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
            nodeSelector:
              scalability: steady
              lifecycle: persistent
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              # prod: whenUnsatisfiable: DoNotSchedule
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: rabbitmqcluster-chat
