name: '[helm][system][argo]'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # otherwise helm upgrade can get stuck and one needs to manually clean the secrets and helm database

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/helm.yaml
      - .github/workflows/argo.system.helm.yaml
      - 20_k8s_workloads/helm/releases/system/argo.yaml
      - 20_k8s_workloads/helm/params.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm.yaml
      - .github/workflows/argo.system.helm.yaml
      - 20_k8s_workloads/helm/releases/system/argo.yaml
      - 20_k8s_workloads/helm/params.yaml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  argo:
    uses: ./.github/workflows/helm.yaml
    strategy:
      fail-fast: false
      matrix:
        release:
          - 20_k8s_workloads/helm/releases/system/argo.yaml
    with:
      file_name: ${{ matrix.release }}
      action: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'apply' || github.event_name == 'pull_request' && 'diff' || 'template' }}
    secrets: inherit
