name: '[k8s][cluster] 🐳'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # otherwise helm upgrade can get stuck and one needs to manually clean the secrets and helm database

on:
  pull_request:
    branches:
      - preview
    paths:
      - .github/workflows/kubectl.yaml
      - .github/workflows/cluster.kubectl.yaml
      - cluster/aks/application-sets/dev.chat.application-set.yaml
  push:
    branches:
      - preview
    paths:
      - .github/workflows/kubectl.yaml
      - .github/workflows/cluster.kubectl.yaml
      - cluster/aks/application-sets/dev.chat.application-set.yaml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  base:
    uses: ./.github/workflows/kubectl.yaml
    strategy:
      fail-fast: false
      matrix:
        release:
          - cluster/aks/application-sets/dev.chat.application-set.yaml
    with:
      file_name: ${{ matrix.release }}
      subscription_id: be4e82ff-bf83-4173-a750-15e807845579
      tenant_id: aeade8c4-d4f7-4ae7-9149-4975fa3a7f91
      client_id: a0e34ba0-b64c-49f4-8d94-1c74d7b3090e
      runner_group_name: ha.uq.dev
      action: ${{ github.event_name == 'push' && github.ref == 'refs/heads/preview' && 'apply' || 'diff' }}
    secrets: inherit
