name: "[k8s]"

on:
  workflow_call:
    inputs:
      file_name:
        description: The path of the file to operate on from root.
        required: true
        type: string
      action:
        description: "Kubectl action to perform: diff or apply."
        default: diff
        type: string

permissions:
  contents: read
  id-token: write

env:
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}

jobs:
  command:
    environment: 20-wl
    runs-on:
      group: hello.azure.unique.dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Azure Login action
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          tenant-id: ${{ vars.TENANT_ID }}
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Set up kubelogin
        uses: azure/use-kubelogin@76597ae0fcbaace21b05e13a2cbf8daee2c6e820 #v1.2
        with:
          kubelogin-version: v0.1.6

      - name: Get AKS context
        uses: azure/aks-set-context@feeca6405be94202afcb1c395616ff29b1811b9f #v4.0.2
        with:
          resource-group: "resource-group-core"
          cluster-name: "aks-cluster"
          admin: 'false'
          use-kubelogin: 'true'

      - name: "🪞 Kubectl Diff"
        if: inputs.action == 'diff'
        run: |
          kubectl diff -f ${{ inputs.file_name }} || true

      - name: "🚀 Kubectl Apply"
        if: inputs.action == 'apply'
        run: |
          kubectl apply -f ${{ inputs.file_name }}
