name: kubectl

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'kubectl command'
        required: true
        default: 'kubectl get pods -A'

permissions:
  contents: read
  id-token: write   # This is required for requesting the JWT

jobs:
  kubectl:
    runs-on:
      group: hello.azure.unique.dev

    steps:
      - name: Azure Login action
        uses: azure/login@v2
        with:
          client-id: "a0e34ba0-b64c-49f4-8d94-1c74d7b3090e"
          tenant-id: "aeade8c4-d4f7-4ae7-9149-4975fa3a7f91"
          subscription-id: "be4e82ff-bf83-4173-a750-15e807845579"

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.1.6

      - name: Get AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "resource-group-core"
          cluster-name: "aks-cluster"
          admin: 'false'
          use-kubelogin: 'true'

      - run: ${{ inputs.command }}
