name: "[kubectl] command"

on:
  workflow_call:
    inputs:
      file_name:
        description: The path of the file to operate on from root.
        required: true
        type: string
      action:
        description: "Kubectl action to perform: diff or apply."
        default: diff
        type: string

permissions:
  contents: read
  id-token: write

env:
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}

jobs:
  command:
    environment: 20-wl
    runs-on:
      group: hello.azure.unique.dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login action
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.TENANT_ID }}
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      # Set up kubelogin for non-interactive authentication with Azure Kubernetes Service (AKS)
      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.1.6

      # Retrieve the Kubernetes context for the AKS cluster
      - name: Get AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "resource-group-core"
          cluster-name: "aks-cluster"
          admin: 'false'
          use-kubelogin: 'true'

      - name: "🪞 Kubectl Diff"
        if: inputs.action == 'diff'
        #! Do not add --debug, it will print secrets!
        # Debug locally as described in repo readme
        # || true will not fail the job if there are changes
        run: |
          kubectl diff -f ${{ inputs.file_name }} || true

      - name: "🚀 Kubectl Apply"
        if: inputs.action == 'apply'
        #! Do not add --debug, it will print secrets!
        # Debug locally as described in repo readme
        run: kubectl apply -f ${{ inputs.file_name }}
