name: '[rel] Mirror Unique Release 🪞'

on:
  workflow_dispatch:
  push:
    branches:
      - preview
    paths:
      - .github/workflows/mirror-unique-artifacts.yaml
      - 20_k8s_workloads/mirror_artifacts/app.unique.yaml

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT
  pull-requests: write # To write comments

env:
  UNIQUECR_USERNAME: ext-hello-azure
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}

jobs:
  clone-release:
    environment: 20-wl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: applications/aks/release
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0

      - name: Azure Login action
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          tenant-id: ${{ vars.TENANT_ID }}
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Install unique-ag/cli
        run: npm install -g @unique-ag/cli@0.5.1

      - name: Mirror public artifacts
        timeout-minutes: 15
        run: |
          qcli az acr import -f app.unique.yaml -u ${{ env.UNIQUECR_USERNAME }} -p ${{ secrets.UNIQUECR_PASSWORD }}
