name: '[rel] Mirror Public Artifacts 🪞'

on:
  workflow_dispatch:
  push:
    branches:
      - preview
    paths:
      - .github/workflows/mirror-public-artifacts.yaml

permissions:
  contents: read
  id-token: write   # This is required for requesting the JWT
  pull-requests: write # To write comments

env:
  UNIQUECR_USERNAME: hello-azure

jobs:
  import:
    environment: 20-wl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: applications/aks/release
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0

      - name: Azure Login action
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          tenant-id: ${{ vars.TENANT_ID }}
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Install unique-ag/cli
        run: npm install -g @unique-ag/cli@0.5.1

      - name: Mirror public artifacts
        timeout-minutes: 15
        run: |
          az acr login --name uniquehelloazure
          qcli mirror images -f io.docker.yaml
          qcli mirror images -f io.ghcr.yaml
          qcli mirror images -f io.quay.yaml
