name: "[tf] [test] Infrastructure 🏗️"
on:
  pull_request:
    branches:
      - preview
    paths:
      - .github/workflows/test.infrastructure.tf.yaml
      - infrastructure/test/**
      - terraform-modules/**
  push:
    branches:
      - preview
    paths:
      - .github/workflows/test.infrastructure.tf.yaml
      - infrastructure/test/**
      - terraform-modules/**
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # To write comments
  id-token: write

jobs:
  automated-plan-apply:
    environment: 10-pm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/test
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
        with:
          terraform_version: 1.10.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=config.auto.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/preview'
        run: terraform apply -auto-approve -input=false
