name: "[test][k8s]"

on:
  workflow_call:
    inputs:
      file_name:
        description: The path of the file to operate on from root.
        required: true
        type: string
      action:
        description: "Kubectl action to perform: diff or apply."
        default: diff
        type: string

permissions:
  contents: read
  id-token: write

env:
  ARM_SUBSCRIPTION_ID: 782871a0-bcee-44fb-851f-ccd3e69ada2a
  ARM_TENANT_ID: aeade8c4-d4f7-4ae7-9149-4975fa3a7f91
  ARM_CLIENT_ID: 93b817fa-3d2c-407f-9a93-3bd40d0029ac

jobs:
  command:
    environment: 20-wl
    runs-on:
      group: ha.uq.test

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Azure Login action
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          tenant-id: aeade8c4-d4f7-4ae7-9149-4975fa3a7f91
          client-id: 93b817fa-3d2c-407f-9a93-3bd40d0029ac
          subscription-id: 782871a0-bcee-44fb-851f-ccd3e69ada2a

      - name: Set up kubelogin
        uses: azure/use-kubelogin@76597ae0fcbaace21b05e13a2cbf8daee2c6e820 #v1.2
        with:
          kubelogin-version: v0.1.6

      - name: Get AKS context
        uses: azure/aks-set-context@feeca6405be94202afcb1c395616ff29b1811b9f #v4.0.2
        with:
          resource-group: "resource-group-core"
          cluster-name: "aks-test"
          admin: 'false'
          use-kubelogin: 'true'

      - name: "🪞 Kubectl Diff"
        if: inputs.action == 'diff'
        run: |
          kubectl diff -f ${{ inputs.file_name }} || true

      - name: "🚀 Kubectl Apply"
        if: inputs.action == 'apply'
        run: |
          kubectl apply -f ${{ inputs.file_name }}
