environments:
  dev:
    values:
      - ../params-dev.yaml
      -
        self:
          namespace: unique
          argo:
            subDomainName: argo
  test:
    values:
      - ../params-test.yaml
      -
        self:
          namespace: unique
          argo:
            subDomainName: argo
---
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo-azure-entra-secret
    chart: oci://ghcr.io/unique-ag/helm-charts/sscsid-keeper
    version: {{ .Values.versions.charts.sscsidKeeper }}
    namespace: {{ .Values.self.namespace }}
    wait: false
    values:
      - ../values/default/argo-azure-entra-secret.yaml.gotmpl
      {{- if isFile (printf "../values/%s/argo-azure-entra-secret.yaml.gotmpl" .Environment.Name) }}
      - ../values/{{ .Environment.Name }}/argo-azure-entra-secret.yaml.gotmpl
      {{- end }}
        

  - name: argo
    needs:
      - argo-azure-entra-secret
    createNamespace: true
    namespace: {{ .Values.self.namespace }}
    chart: argo/argo-cd
    version: {{ .Values.versions.charts.argo }} # https://github.com/argoproj/argo-helm/releases
    wait: false
    values:
      - ../values/default/argo.yaml.gotmpl
      {{- if isFile (printf "../values/%s/argo.yaml.gotmpl" .Environment.Name) }}
      - ../values/{{ .Environment.Name }}/argo.yaml.gotmpl
      {{- end }}
